#include<stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int fib(int);

int main()
{
    int max = 4000000;
    int fibtemp = 0;
    int add = 0;

    for (int i = 0; i < 40; i++)
    {
        fibtemp = fib(i);

        if (fibtemp > max)
            break;
        else if (fibtemp % 2 == 0)
        {
            add = add + fibtemp;
        }
    }
    printf("%d\n", add);
}

int fib(int n)
{
    int front = 0;
    int end = 1;
    int fib = 0;

    if (n == 0)
        return 0;
    else
    {
        for (int i = 0; i < n; i++)
        {
            fib = front + end;
            front = end;
            end = fib;
        }
        return fib;
    }
}
